# Generated by Django 3.0.2 on 2020-07-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('incident_location', models.TextField()),
                ('intial_severity', models.CharField(max_length=100)),
                ('suspected_cause', models.TextField()),
                ('action_taken', models.TextField()),
                ('sub_incident_types', models.TextField()),
            ],
        ),
    ]
